/// Flutter icons CustomAppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomAppIcons
///      fonts:
///       - asset: fonts/CustomAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomAppIcons {
  CustomAppIcons._();

  static const _kFontFam = 'CustomAppIcons';
  static const String? _kFontPkg = null;

  static const IconData return_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pressure = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloudy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunrise = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sunset = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_filled = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
